### ISSUE TITLE
infinibox-csi-driver not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by cotjoey** [Infinidat/infinibox-csi-driver#107]
Hello,

I am using Kubernetes 1.20. I create a PersistentVolume (PV) and PersistentVolumeClaim (PVC). I import an existing volume using the steps at https://support.infinidat.com/hc/en-us/articles/360008917097 (Importing an existing NFS PV).

This PV is for a Postgres DB to persist data.

When I reboot my node to test a "failure" scenario, I get an the following error in my Postgres pod log:

```
Warning  FailedMount       45m (x10 over 45m)    kubelet  MountVolume.SetUp failed for volume "csi-78ce24e2a4" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name infinibox-csi-driver not found in the list of registered CSI drivers
```

When I look at the CSI Driver list, it does exist:
```
$ sudo kubectl get csidriver
NAME                   ATTACHREQUIRED   PODINFOONMOUNT   MODES        AGE
infinibox-csi-driver   true             true             Persistent   12h
```

I also have one storage class:
```
$ sudo kubectl get storageclass
NAME                           PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ibox-nfs-storageclass-retain   infinibox-csi-driver   Retain          Immediate           true                   12h
```

The is also a DaemonSet that the helm install command installs and runs on each node:
```
NAMESPACE                NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                             AGE
infi                     csi-infinibox-node                 8         8         8       8            8           <none>                                                                    12h
```

From the message in the error log, it seems that the CSI Driver needs to be a DaemonSet running on all nodes in the cluster, but it's not what I see from the pod listing (I have 8 nodes):

```
infi                     pod/csi-infinibox-driver-0                     5/5     Running       10         127m
infi                     pod/csi-infinibox-node-2j7ff                   2/2     Running       6          127m
infi                     pod/csi-infinibox-node-4g9tv                   2/2     Running       4          127m
infi                     pod/csi-infinibox-node-4n5kt                   2/2     Running       4          127m
infi                     pod/csi-infinibox-node-fq9fz                   2/2     Running       4          127m
infi                     pod/csi-infinibox-node-fqzc8                   2/2     Running       4          127m
infi                     pod/csi-infinibox-node-hx9hj                   2/2     Running       4          127m
infi                     pod/csi-infinibox-node-kpgjm                   2/2     Running       4          127m
infi                     pod/csi-infinibox-node-tx5zd                   2/2     Running       4          127m
```

I am wondering if I am set up correctly or need additional configuration for my pods to recover after a failure using the CSI Driver.

Thank you for any help you can provide.

Joey

**Comment by gadekarnitesh** [comment]
Hi @cotjoey ,
Could you please share the PV .yaml file and `kubectl describe csidriver` command output.

**Comment by cotjoey** [comment]
Hello @gadekarnitesh ,

Here is the YAML file I use to import the existing PV (I use envsubst to replace the $VAR values):

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: infinibox-csi-driver
  name: $ARGO_POSTGRES_PV_NAME
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: $ARGO_POSTGRES_PV_STORAGE
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: infi
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: infi
    driver: infinibox-csi-driver
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: infi
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: infi
    volumeAttributes:
      ipAddress: $ARGO_POSTGRES_PV_IP
      volPathd: $ARGO_POSTGRES_PV_VOLPATHD
      storage_protocol: $ARGO_POSTGRES_PV_STORAGEPROTOCOL
      exportID: "$ARGO_POSTGRES_PV_EXPORTID"
    volumeHandle: $ARGO_POSTGRES_PV_VOLUMEHANDLE
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibox-nfs-storageclass-retain
  volumeMode: Filesystem
```

Describe on the CSIDriver:

```
$ sudo kubectl describe csidriver infinibox-csi-driver
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
Name:         infinibox-csi-driver
Namespace:    
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: csi-infinibox
              meta.helm.sh/release-namespace: infi
API Version:  storage.k8s.io/v1beta1
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2021-10-19T13:57:54Z
  Managed Fields:
    API Version:  storage.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        f:attachRequired:
        f:fsGroupPolicy:
        f:podInfoOnMount:
        f:volumeLifecycleModes:
    Manager:         helm
    Operation:       Update
    Time:            2021-10-19T13:57:54Z
  Resource Version:  254888
  UID:               4686b99e-2cbd-431f-945a-cd6e5f037648
Spec:
  Attach Required:    true
  Fs Group Policy:    ReadWriteOnceWithFSType
  Pod Info On Mount:  true
  Volume Lifecycle Modes:
    Persistent
Events:  <none>
```

Thank you,
Joey
